# Association Rule Technique.

***It finds the interesting association and relationship among large dataset of data items.this rule shows how frequently
    a itemset occures in a transaction.***

In [3]:
data=[['milk','bread','rice','book'],
      ['bread','jam','book','pen'],
      ['jam','milk','bread','rice','eggs'],
      ['rice','eggs','pen','book'],
      ['eggs','pen','milk','bread','jam'],
      ['eggs','rice','bread','jam']]

Example 1:
        {Rice,Eggs}={X,Y}
            min_support=0.3 (take as example)
            min_confidence=0.6

        support(s)=(X union Y)/N = 3/6 = 0.5
        confidence(c)=(X union Y)/x = 3/4=0.75

        0.5>=min_support
        0.75>=minn_confidence

    Therefore   {Rice,Eggs} as a rule

Example 2:
        {Pen,Book}={X,Y}
            min_support=0.3 (take as example)
            min_confidence=0.6

        support(s)=(X union Y)/N = 2/6=0.33
        confidence(c)=(X union Y)/x=2/3=0.66

        0.33>=min_support
        0.66>=minn_confidence

    Therefore   {Pen,Book} as a rule

In [4]:
from mlxtend.preprocessing import TransactionEncoder
te= TransactionEncoder()
te_array=te.fit_transform(data)
te_array

array([[ True,  True, False, False,  True, False,  True],
       [ True,  True, False,  True, False,  True, False],
       [False,  True,  True,  True,  True, False,  True],
       [ True, False,  True, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True, False],
       [False,  True,  True,  True, False, False,  True]])

In [5]:
import pandas as pd
df=pd.DataFrame(te_array)
df

       0      1      2      3      4      5      6
0   True   True  False  False   True  False   True
1   True   True  False   True  False   True  False
2  False   True   True   True   True  False   True
3   True  False   True  False  False   True   True
4  False   True   True   True   True   True  False
5  False   True   True   True  False  False   True

In [6]:
df=pd.DataFrame(te_array,columns=te.columns_)
df

    book  bread   eggs    jam   milk    pen   rice
0   True   True  False  False   True  False   True
1   True   True  False   True  False   True  False
2  False   True   True   True   True  False   True
3   True  False   True  False  False   True   True
4  False   True   True   True   True   True  False
5  False   True   True   True  False  False   True

In [7]:
df=pd.DataFrame(te_array,columns=te.columns_).astype(int)
df

   book  bread  eggs  jam  milk  pen  rice
0     1      1     0    0     1    0     1
1     1      1     0    1     0    1     0
2     0      1     1    1     1    0     1
3     1      0     1    0     0    1     1
4     0      1     1    1     1    1     0
5     0      1     1    1     0    0     1

In [43]:
from mlxtend.frequent_patterns import apriori
itemset=apriori(df,min_support=0.5,use_colnames=True)
itemset

C:\Users\Asus\AppData\Local\Programs\Orange\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support            itemsets
0   0.500000              (book)
1   0.833333             (bread)
2   0.666667              (eggs)
3   0.666667               (jam)
4   0.500000              (milk)
5   0.500000               (pen)
6   0.666667              (rice)
7   0.500000       (eggs, bread)
8   0.666667        (jam, bread)
9   0.500000       (milk, bread)
10  0.500000       (bread, rice)
11  0.500000         (eggs, jam)
12  0.500000        (eggs, rice)
13  0.500000  (eggs, jam, bread)

In [45]:
from mlxtend.frequent_patterns import association_rules
res=association_rules(itemset,metric='confidence',min_threshold=0.7)
res

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(eggs),(bread),0.666667,0.833333,0.500000,0.75,0.900,1.0,-0.055556,0.666667,-0.250000,0.50,-0.50,0.675
1,(jam),(bread),0.666667,0.833333,0.666667,1.00,1.200,1.0,0.111111,inf,0.500000,0.80,1.00,0.900
2,(bread),(jam),0.833333,0.666667,0.666667,0.80,1.200,1.0,0.111111,1.666667,1.000000,0.80,0.40,0.900
3,(milk),(bread),0.500000,0.833333,0.500000,1.00,1.200,1.0,0.083333,inf,0.333333,0.60,1.00,0.800
4,(rice),(bread),0.666667,0.833333,0.500000,0.75,0.900,1.0,-0.055556,0.666667,-0.250000,0.50,-0.50,0.675
5,(eggs),(jam),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
6,(jam),(eggs),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
7,(eggs),(rice),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
8,(rice),(eggs),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
9,"(eggs, jam)",(bread),0.500000,0.833333,0.500000,1.00,1.200,1.0,0.083333,inf,0.333333,0.60,1.00,0.800
10,"(eggs, bread)",(jam),0.500000,0.666667,0.500000,1.00,1.500,1.0,0.166667,inf,0.666667,0.75,1.00,0.875
11,"(jam, bread)",(eggs),0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
12,(eggs),"(jam, bread)",0.666667,0.666667,0.500000,0.75,1.125,1.0,0.055556,1.333333,0.333333,0.60,0.25,0.750
13,(jam),"(eggs, bread)",0.666667,0.500000,0.500000,0.75,1.500,1.0,0.166667,2.000000,1.000000,0.75,0.50,0.875